### ISSUE TITLE
Training issue

### ISSUE THREAD

**Issue by liuallen871219** [UT-Austin-RPL/GIGA#10]
I follow the command `python scripts/train_giga.py --dataset /path/to/new/data --dataset_raw /path/to/raw/data` , and change the path of data(pack).
At the beginning of training, I got the msg
import libmesh failed
import libkdtree failed
import utils failed
![Screenshot from 2021-12-12 00-17-38](https://user-images.githubusercontent.com/40296275/145683857-72fde018-a56c-48be-9bef-c31d632394d8.png)
I still can continue to train.
But I got an error msg after finishing the first epoch
![Screenshot from 2021-12-12 00-25-31](https://user-images.githubusercontent.com/40296275/145683993-2b498aaf-c744-4043-a040-f390d074dee1.png)

I don't know what happened

**Comment by Steve-Tod** [comment]
Hi, the import errors are just warnings and that's OK. For the second error, I think the reason is that you didn't generate the occupancy data or the occupancy data is broken. You can follow [here](https://github.com/UT-Austin-RPL/GIGA#save-occupancy-data) to regenerate the occupancy data.

**Comment by liuallen871219** [comment]
Thanks for your reply. that's very helpful
I have followed the instruction to generate the occupancy data.
I changed the value of num_worker (data loader) to 1.  The error is gone.
I think it might be the multiprocessing issue for the dataloder.

**Comment by Steve-Tod** [comment]
Not sure why that happens. But good to know it works at the end😊.
