### ISSUE TITLE
visualize grasp afforance

### ISSUE THREAD

**Issue by ccc1711** [UT-Austin-RPL/GIGA#11]
May I ask what software did you use to visualize the grasp afforance? 
colored like this。。。
![1647106843(1)](https://user-images.githubusercontent.com/71708754/158028814-4be2bb4c-0f63-4e73-9539-3ca907857d2e.jpg)

**Comment by Steve-Tod** [comment]
Hi, you can refer to this code snippets: https://github.com/UT-Austin-RPL/GIGA/blob/d67c4388d334babe6c11c1555a6e848fb4828c84/src/vgn/utils/visual.py#L101

**Comment by ccc1711** [comment]
ok，and how can I get the size of feature map for each layer?

**Comment by Steve-Tod** [comment]
I think you can print the size of the different layers of the network and compute the size of the feature map.

**Comment by ccc1711** [comment]
Is the “TSDF-3DCNN-PointNet-3DUnet” process reasonable?

**Comment by Steve-Tod** [comment]
Sorry for the late reply, I didn't see this earlier. What do you mean by “TSDF-3DCNN-PointNet-3DUnet”?

**Comment by ccc1711** [comment]
It's nothing ,i was wrong, and  is the process of projection and aggregation implemented in  **def generate_frid_features()**?

**Comment by Steve-Tod** [comment]
Yeah, that's right.
