### ISSUE TITLE
Corruption or core dumped

### ISSUE THREAD

**Issue by Jonas-LUOJIAN** [UT-Austin-RPL/GIGA#13]
hi, when i run the command:
`python scripts/construct_dataset_parallel.py --num-proc 40 --single-view --add-noise dex /path/to/raw/data /path/to/new/data`
An error like this:
![image](https://user-images.githubusercontent.com/73736897/168313035-ded86e2e-466b-4bab-837b-5de2df8a0dfa.png)
and i change the num-proc into 1
An error like this:
![1652454652(1)](https://user-images.githubusercontent.com/73736897/168313547-a4ea97cb-b26e-4fbb-926d-a036a3094b18.png)

**Comment by Steve-Tod** [comment]
It seems there's some problem with pybullet, can you do some debugging and locate which line of the code throws this error?

**Comment by hooyahliu** [comment]
> It seems there's some problem with pybullet, can you do some debugging and locate which line of the code throws this error?


Hello, I have also encountered this issue and have located the program position as follows:
https://github.com/UT-Austin-RPL/GIGA/blob/d67c4388d334babe6c11c1555a6e848fb4828c84/src/vgn/perception.py#L111C11-L111C11

In the original VGN, open3d was not used to directly obtain the voxel grid, so I did not encounter this error in the original VGN program.
https://github.com/ethz-asl/vgn/blob/d7af0622433f52ae88ebe81533f12b46b33e951a/src/vgn/perception.py#L107C14-L107C15

Does replacing this location with the VGN program have any impact?

**Comment by hooyahliu** [comment]
To downgrade the Python version to 3.8 and use Open3D version 0.12, the issue was resolved. 


> It seems there's some problem with pybullet, can you do some debugging and locate which line of the code throws this error?

**Comment by Steve-Tod** [comment]
> To downgrade the Python version to 3.8 and use Open3D version 0.12, the issue was resolved.
> 
> > It seems there's some problem with pybullet, can you do some debugging and locate which line of the code throws this error?

Thanks for experimenting and letting us know!
