### ISSUE TITLE
Visualizing input TSDFs and grasp

### ISSUE THREAD

**Issue by ishikaalunawat** [UT-Austin-RPL/GIGA#14]
Hi,

I'm trying to obtain:
1. TSDFs: A 3D visualization of the input TSDFs.
2. Grasp affordance: The visuals of the grasp affordance are not getting logged under the `data/experiments/<>/meshes` folder. There are no files with `<name>_aff.obj>` getting logged/saved (although the scenes are still getting saved as  `<name>_aff.obj>` .

Please let me know what I can do achieve the above.

**Comment by Steve-Tod** [comment]
1. I visualize the TSDF with matplotlib in a jupyter notebook so I don't have a well-written function for that. I think you can save `tsdf_vol` to numpy array [here](https://github.com/UT-Austin-RPL/GIGA/blob/d67c4388d334babe6c11c1555a6e848fb4828c84/src/vgn/detection_implicit.py#L50) and visualize offline.
2. I think running [this script](https://github.com/UT-Austin-RPL/GIGA/blob/main/scripts/sim_grasp_save_scene.py) with argument `--vis` should give you the affordance visualization. Can you try it?

**Comment by ishikaalunawat** [comment]
Hey,
1. Thanks I’ll try that out!
2. I did use the `—vis` command but as I explained above, no affordance related files get saved as obj. [Btw, I’m using the pretrained giga model on piles dataset]

**Comment by ishikaa25** [comment]
> 

1. Works!
2. I have used `--vis` command and the following:
    a. In `clutter_removal.py`: Tried saving to different path inside the`log_mesh`, doesn't work
    b. In `clutter_removal.py`: Added a line `visual_mesh.export(f'newf/composed.obj', file_type='obj')` in the loop, doesn't work

**Comment by ishikaalunawat** [comment]
> Hey,
> 
> 1. Thanks I’ll try that out!
> 2. I did use the `—vis` command but as I explained above, no affordance related files get saved as obj. [Btw, I’m using the pretrained giga model on piles dataset]

1. Works! Thank you
2. Works, but I added a line in `clutter_removal.py` to export: `visual_mesh.export('<path-to-save>',file_type='obj')`
