### ISSUE TITLE
Visualizing on custom dataset

### ISSUE THREAD

**Issue by ishikaalunawat** [UT-Austin-RPL/GIGA#16]
What is the coordinate system / reference you take for adding the grasp visual in `grasp2mesh()`? 

I tweaked your code a bit to run it on my dataset, but the gripper is way farther from the object mesh.
I ran the pre-trained model and got the best grasp params (affordance, rotation, width and center). Here is the code I used to visualize:

<details>

<summary>Code:</summary>

```
# Loading custom data mesh
mesh = trimesh.load('mydata/processed/meshes/map_{}.obj'.format(scene_id),force='scene')
grasp = Grasp(Transform(ori, pos, width)

finger_depth = 0.05
color = np.array([0, 250, 0, 180]).astype(np.uint8)
radius = 0.1 * finger_depth
w, d = grasp.width, finger_depth
pose = grasp.pose * Transform(Rotation.identity(), [0.0, -w / 2, d / 2])
scale = [radius, radius, d]
left_finger = trimesh.creation.cylinder(radius,
                                        d,
                                        transform=pose.as_matrix())
scene.add_geometry(left_finger, 'left_finger')

# right finger
pose = grasp.pose * Transform(Rotation.identity(), [0.0, w / 2, d / 2])
scale = [radius, radius, d]
right_finger = trimesh.creation.cylinder(radius,
                                            d,
                                            transform=pose.as_matrix())
scene.add_geometry(right_finger, 'right_finger')

# wrist
pose = grasp.pose * Transform(Rotation.identity(), [0.0, 0.0, -d / 4])
scale = [radius, radius, d / 2]
wrist = trimesh.creation.cylinder(radius,
                                    d / 2,
                                    transform=pose.as_matrix())
scene.add_geometry(wrist, 'wrist')

# palm
pose = grasp.pose * Transform(
    Rotation.from_rotvec(np.pi / 2 * np.r_[1.0, 0.0, 0.0]),
    [0.0, 0.0, 0.0])
scale = [radius, radius, w]
palm = trimesh.creation.cylinder(radius, w, transform=pose.as_matrix())
scene.add_geometry(palm, 'palm')
scene.add_geometry(trimesh.creation.axis())
```

**Comment by Steve-Tod** [comment]
I think it should be in [0, 0.3] * 3 coordinates.

**Comment by ishikaalunawat** [comment]
> I think it should be in [0, 0.3] * 3 coordinates.

You mean the scale of range of the grasp query or the scene?

**Comment by Steve-Tod** [comment]
> > I think it should be in [0, 0.3] * 3 coordinates.
> 
> 
> 
> You mean the scale of range of the grasp query or the scene?

The scale of the scene.

**Comment by ishikaalunawat** [comment]
> > > I think it should be in [0, 0.3] * 3 coordinates.
> > 
> > 
> > You mean the scale of range of the grasp query or the scene?
> 
> The scale of the scene.

Right.
So basically I made the TSDF (voxels) such that each voxel has a size 0.0075 cm and so the TSDF has length of 30cm in a (40,40,40) grid.

But in Trimesh my scene seems to be shifted from the origin, so how did you scale it in your case? Is this just a trimesh thing?

**Comment by Steve-Tod** [comment]
> > > > I think it should be in [0, 0.3] * 3 coordinates.
> 
> > > 
> 
> > > 
> 
> > > You mean the scale of range of the grasp query or the scene?
> 
> > 
> 
> > The scale of the scene.
> 
> 
> 
> Right.
> 
> So basically I made the TSDF (voxels) such that each voxel has a size 0.0075 cm and so the TSDF has length of 30cm in a (40,40,40) grid.
> 
> 
> 
> But in Trimesh my scene seems to be shifted from the origin, so how did you scale it in your case? Is this just a trimesh thing?

Does it look like a uniform shift?  Because the prediction space of implicit functions is [-0.5, 0.5], I scale and shift the output into [0, 0.3] in the visualization function.

**Comment by ishikaalunawat** [comment]
Thanks for the help! To sum up the ranges:
> input query points : `[0,0.3]`
> output of implicit function : `[-0.5,0.5]` which is then scaled & shifted to get it in `[0,0.3]` 

Is this correct?

**Comment by Steve-Tod** [comment]
> Thanks for the help! To sum up the ranges:
> 
> > input query points : `[0,0.3]`
> > output of implicit function : `[-0.5,0.5]` which is then scaled & shifted to get it in `[0,0.3]`
> 
> Is this correct?

Yes!

**Comment by ishikaa25** [comment]
So right now,
My grasp query points/centers are generated like this: 
`pos = np.random.uniform(-0.5, 0.5, (self.num_point,3))`

My actual (input) data is as follows:
1. Depth image: `1280x720 px`
2. TSDF: 
 a. `resolution = 100` --> `(40,40,40)` [truncated manually using numpy slicing since the objects always only lie in this range anyway]
 b. `length = 0.75`
 (Thus, I have a `(40,40,40)` TSDFs voxels, each of length `0.0075` (same as yours)
3. Pointcloud: points scaled from `[0, 0.75]` --> `[0, 0.3]`
4. Meshes: `extents = [0.745576, 0.304891, 0.483592]` 
(So, maybe because I picked the resolution as 100, the mesh extends upto 0.0075*100 = 0.75

How I visualize (code in first comment):
1. I use the GIGA-pile pretrained model to save best grasps (`quality`, `rot`, `width` and `pos[best_quality]`) from the input TSDF voxels and `pos`
2. The grasp centers I get are in the range `[0, 0.3]`, hence I skip the step of scaling and transformation.
3. The remaining values I've used are the same as in your code yet scaling and orientation of the gripper wrt scene mesh are totally off (not uniform for all scenes). 

It'd be great if you could help me out on this an give your suggestions!

**Comment by ishikaalunawat** [comment]
I needed some help regarding sampling of query points. I've used your `sample_grasp_point()` function. But how did you choose the threshold value for `normal[2] > -0.1` for selecting a surface point? The problem I faced is while sampling points, points **inside the object** are also present.
For reference,
Image of the point cloud   | Normals of point clound
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/63252702/177339023-2eb00c89-cd08-4779-9c87-421ebc201a43.png#left) | ![image](https://user-images.githubusercontent.com/63252702/177339912-cd7ff0cf-1783-41ed-b842-76744391734e.png)





Note: I've used `pcd.estimate_normals()` to get the normals.

**Comment by Steve-Tod** [comment]
Hi, it's OK to sample points inside the object, because in that case, the gripper would collide with the object before getting to the target position, and the current data generation script would detect that collision and mark the grasp as a failure.
