### ISSUE TITLE
visual

### ISSUE THREAD

**Issue by September-Ice** [UT-Austin-RPL/GIGA#18]
![image](https://user-images.githubusercontent.com/63761098/176859840-10a31847-211d-4779-8bc4-9ee193a39aa0.png)
Hello, how to the get these figures?

**Comment by Steve-Tod** [comment]
Run this script (https://github.com/UT-Austin-RPL/GIGA/blob/main/scripts/eval_geometry_voxel.py) and it will evaluate the geometry and save the extracted mesh.
