### ISSUE TITLE
How to use GIGA on real robot?

### ISSUE THREAD

**Issue by estellexky** [UT-Austin-RPL/GIGA#19]
Hello! Thanks for your excellent work! I would like to use GIGA on real robot grasping, could you please provide relevant files (.py, yaml, launch...)?

**Comment by Steve-Tod** [comment]
Hi, our real robot code is pretty messy and we haven't clean it yet. It's mainly based on the code from [VGN](https://github.com/ethz-asl/vgn). I would suggest looking into their code :-).

**Comment by estellexky** [comment]
OK, thanks~
