### ISSUE TITLE
GIGA weights

### ISSUE THREAD

**Issue by trungpham2606** [UT-Austin-RPL/GIGA#2]
Dear @yukezhu @Steve-Tod 
Can you publicpretrained weights of GIGA and GIGA_AFF ?

**Comment by Steve-Tod** [comment]
Hi, I updated the pretrained weights in the [google drive](https://drive.google.com/file/d/13vlsR9797qW097bYXhJ8lN8b7Eb_UdgD/view?usp=sharing). It's in the `data/models`.
