### ISSUE TITLE
Installation error:  "  LINK : fatal error LNK1181: can not open input file“m.lib”  "

### ISSUE THREAD

**Issue by QiNaN-Zhang** [UT-Austin-RPL/GIGA#21]
Hello! I just began my robotics research which is very related to yours' . I am trying to follow your work in Github.
When I carried out the step 4 of Installation, firstly it said the cl.exe could not be found, so I installed Visual Studio 2017 and set the path of environment variables, like following:
env variable **"path"**:
![59c970039d64cea71a8c78e4c647b1d](https://user-images.githubusercontent.com/81978063/200129016-1db64050-a891-4936-8c9e-41da28444fb8.png)
env variable **"LIB"**:
![68a92ee85ced7d4b162a7111003f2fa](https://user-images.githubusercontent.com/81978063/200129084-dcea191f-d06f-4651-a8af-a7b3bd653a8d.png)
env variable **"INCLUDE"**:
![cc9ace3eadb75bf5be89752912ebccd](https://user-images.githubusercontent.com/81978063/200129090-e1fb489c-f694-4586-abed-eebebd91d55a.png)

But an error still occurred: **LINK : fatal error LNK1181: can not open input file“m.lib”** . The specific output in the command line:
![1fe4b6571fd38fdb3cc17ff043529f5](https://user-images.githubusercontent.com/81978063/200128922-5fee09c6-a44c-440a-9794-3c19f0d27e6d.png)

I thought it might still caused by libpath or something, but I could not fix it after trials. I think it will definitely affect the following steps of installation or data generation so it is annoying.
Do you have some ideas or suggestions to fix it? Thanks a lot!

**Comment by Steve-Tod** [comment]
Hi, this step is building the extensions for ConvONet, I'm not sure if it is designed to work on Windows. I would suggest installing a [Windows Linux subsystem](https://learn.microsoft.com/en-us/windows/wsl/install) and carrying out experiments in the subsystem.

**Comment by QiNaN-Zhang** [comment]
Ok，thanks! I have just fixed the error by adjusting the codes(about libraries). But there will be other problems. I would consider carrying out experiments in Linux. So you recommend to use WSL on win10? I do not know if it will fit well with my NVIDIA.

**Comment by Steve-Tod** [comment]
I remember installing nvidia driver and cuda-related libraries on WSL on win10 and it works quite well.

**Comment by QiNaN-Zhang** [comment]
I will try. Thanks!
