### ISSUE TITLE
About NVIDIA Driver in WSL2

### ISSUE THREAD

**Issue by QiNaN-Zhang** [UT-Austin-RPL/GIGA#22]
I have tried to install the program in wsl2 using ubuntu. If I use command "nvidia-smi' in linux, I can get a result:
<img width="497" alt="error1" src="https://user-images.githubusercontent.com/81978063/201684031-5ccb4426-e37e-4bfa-b99e-935f04b0ba6d.png">

But when I try to install cuda from nvidia by 
wget https://developer.download.nvidia.com/compute/cuda/11.5.0/local_installers/cuda_11.5.0_495.29.05_linux.run
sudo sh cuda_11.5.0_495.29.05_linux.run
It will warn like that:
![error](https://user-images.githubusercontent.com/81978063/201683907-a042e62c-6f4e-422c-88f5-891fcb6fa91e.png)

Thus is it necessary to download and install the **nvidia driver for linux 64-bit** in nvidia website? I tried to do that, but I can not install it locally in wsl2-ubuntu system. It reminded that there is not an NVIDIA GPU in this system. Thanks!

**Comment by Steve-Tod** [comment]
At the end of the log you can see that you can use `sudo cuda_11.5.0_495.29.05_linux.run -silent -driver` to install driver. And from `nvidia-smi` it seems you already have cuda driver installed. You can try install pytorch and run `a = torch.randn(3).cuda()` and see if there's any error.

**Comment by QiNaN-Zhang** [comment]
Thus if I run it smoothly, it proves cuda will be used in experiments without problem?

**Comment by QiNaN-Zhang** [comment]
And when I tried to build the ConvOnets as step 4 in installation, some warnings happened:
<img width="815" alt="21126abd3387f4b6b90f431c2c91fd0" src="https://user-images.githubusercontent.com/81978063/201942078-d7cbdc8c-9aef-4f43-867e-c7bffd115cf5.png">
If it was caused by differentt versions of related packages? And it will affect future experiments like generating or training? Thanks!!

**Comment by Steve-Tod** [comment]
The warning is normal. It won't affect the experiments.

**Comment by QiNaN-Zhang** [comment]
Thanks！I am now tring to process data and train the models.
