### ISSUE TITLE
[Question] How to get the 3d reconstruction at inference time?

### ISSUE THREAD

**Issue by chisarie** [UT-Austin-RPL/GIGA#24]
Hi, thank you very much for releasing this project!

I have a quick question regarding inference with GIGA. I see that I can predict grasps by using the `VGNImplicit` class and calling its `__call__` function. When visualize is set to `true`, that function returns `grasps, scores, toc, composed_scene`, see here:
https://github.com/UT-Austin-RPL/GIGA/blob/d67c4388d334babe6c11c1555a6e848fb4828c84/src/vgn/detection_implicit.py#L83

But from my understanding, the returned `composed_scene` is just the input tsdf + the added grasps, it does not contain the 3d reconstruction. Is that correct?

So my question is, how do I get the 3d reconstruction? To me it seems that the `p_tsdf` argument and the `self.decoder_tsdf` are relevant here, but I am not sure how to use them. 
https://github.com/UT-Austin-RPL/GIGA/blob/d67c4388d334babe6c11c1555a6e848fb4828c84/src/vgn/ConvONets/conv_onet/models/__init__.py#L64

Assuming this is the right way to get the 3d reconstruction, what should I pass as `p_tsdf`? And then, how do I process and visualize the output of `decoder_tsdf`? 

Thank you very much in advance, I am looking forward to hearing from you!

**Comment by Steve-Tod** [comment]
Hi, thanks for your interest in our work! The `composed_scene` here is the ground truth mesh and the added grasps. It's for visualization. If you want to get the 3D reconstruction, you can refer to this line: https://github.com/UT-Austin-RPL/GIGA/blob/d67c4388d334babe6c11c1555a6e848fb4828c84/scripts/eval_geometry_voxel.py#LL80C32-L80C32.

**Comment by chisarie** [comment]
Thank you for the fast response. What is the argument `pc_in` exactly? Is it the raw pointcloud from the camera, including all objects and the table they are sitting on? 
I am trying to do inference from a depth camera I have in real life, not from the simulation

**Comment by Steve-Tod** [comment]
Hi, we crop the raw point cloud to remove the table surface and only keep the objects.
https://github.com/UT-Austin-RPL/GIGA/blob/d67c4388d334babe6c11c1555a6e848fb4828c84/scripts/construct_dataset_parallel.py#L34

**Comment by chisarie** [comment]
Hi, so I think I managed to put together a working script. Could you please let me know if this (pseudocode) looks correct? Thank you very much in advance.

```python
from vgn.detection_implicit import VGNImplicit  # GIGA
from vgn.perception import TSDFVolume, create_tsdf
from vgn.ConvONets.conv_onet.generation import Generator3D

O_RESOLUTION = 40
O_SIZE = 0.3  # Meters --> I saw this somewhere in the repo
O_VOXEL_SIZE = O_SIZE / O_RESOLUTION

giga_model = VGNImplicit(
    model_path=model_path,
     model_type="giga",
     visualize=vis,
     best=True,
     qual_th=0.75,
     force_detection=True,
     out_th=0.1,
     select_top=False,
)
generator = Generator3D(
    self.giga_model.net,
    device=self.giga_model.device,
    input_type='pointcloud',
    padding=0,
)
tsdf_volume = create_tsdf(
    size=O_SIZE,
    resolution=O_RESOLUTION,
    depth_imgs=np.expand_dims(depth, axis=0),
    intrinsic=self.camera_intrinsic,
    extrinsics=np.expand_dims(camera_pose, axis=0),
)

pc_torch = torch.tensor(tsdf_volume.get_grid())
pred_mesh, _ = generator.generate_mesh({'inputs': pc_torch})

# scale back to original size
scale_matrix = np.eye(4)
scale_matrix[:3, :3] *= O_SIZE
pred_mesh.apply_transform(scale_matrix)
```

**Comment by Steve-Tod** [comment]
Yes, I think it's correct. I just re-ran the code and found input to `generate_mesh` is with size `torch.Size([1, 40, 40, 40])`, so it's a tsdf grid.

**Comment by chisarie** [comment]
Great, thank you!
