### ISSUE TITLE
No module named vgn

### ISSUE THREAD

**Issue by HongqingThomas** [UT-Austin-RPL/GIGA#25]
when I try to run the command:

python scripts/sim_grasp_multiple.py --num-view 1 --object-set (packed/test | pile/test) --scene （packed ｜ pile) --num-rounds 100 --sideview --add-noise dex --force --best --model /path/to/model --type (vgn | giga | giga_aff) --result-path /path/to/result

it shows an error that no module named 'vgn', it seems like sim_grasp_multiple.py fails to import src/vgn or any file under vgn, I'm wondering how to fix it.

**Comment by Steve-Tod** [comment]
Hi, did you follow the [installation instructions](https://github.com/UT-Austin-RPL/GIGA#installation)? After installing the required packages, you need to run `pip install -e .` to install the library as a local package.

**Comment by HongqingThomas** [comment]
Thanks for the suggestion, now the problem is solved.
