### ISSUE TITLE
libmesh failed!

### ISSUE THREAD

**Issue by zihanwang0422** [UT-Austin-RPL/GIGA#26]
In this step:"python scripts/save_occ_data_parallel.py /home/wzh/GIGA-main/data/raw_data 100000 2 --num-proc 40"
I have this error:
import libmesh failed!
Total jobs: 0, CPU num: 40

but I have installed libmesh 0.0.6

**Comment by Steve-Tod** [comment]
It's from [here](https://github.com/UT-Austin-RPL/GIGA/blob/d67c4388d334babe6c11c1555a6e848fb4828c84/src/vgn/utils/implicit.py#L6). Have you successfully installed the ConvONets requirements using this command?
`python scripts/convonet_setup.py build_ext --inplace`

**Comment by zihanwang0422** [comment]
I have solved it!
Thanks a lot!!
