### ISSUE TITLE
question about GIGA(HR)

### ISSUE THREAD

**Issue by HongqingThomas** [UT-Austin-RPL/GIGA#27]
hi, first of all, thanks for your contribution in the community!
My question is about some detail of randomly query grasp sample given a trained model.

In VGN, after we sample grasp candidates, we have to mask out those voxles which distance to the nearest surface is smaller than the finger depth. This is because we can not train sample in such case during self-supervised learning, so we can not inlcude this configuration into model. 

It seems like we have to use TSDF information, which is a sparse information, has a shape of 1 * 40 * 40 * 40 in the experiment. I feel like in GIGA, we still needs this section for grasp detection, how can we gather the TSDF information of candidates if we sample the candidate randomly?

**Comment by Steve-Tod** [comment]
Hi, thank you for your interest in our work and the deep investigation!

I'm not sure if I understand your question correctly. I guess you are asking about how to sample grasp candidates in arbitrary resolution, given the TSDF with fixed resolution.

Suppose we want to sample grasp candidates at 80*80*80 resolution, we can first get the valid voxels using TSDF of 40 resolution. Then we can upsample the valid voxels into 80 resolution, and use the points inside the valid voxels to query grasping parameters. The key point here is that the valid voxel grid is easily interpolable, but the grasp parameters are not, and that's where the implicit representation comes into play.
