### ISSUE TITLE
Can't log _aff.obj when running sim_grasp_multiple.py

### ISSUE THREAD

**Issue by HongqingThomas** [UT-Austin-RPL/GIGA#29]
Hi, 
Thanks for your contribution to the community!

Q1. When I try to run the sim_grasp_multiple.py use your command in readme.md( I add --vis already), the system can only log _scene.obj while can not log _aff.obj.

##
def log_mesh(self, scene_mesh, aff_mesh, name):
        aff_mesh.export(self.mesh_dir / (name + "_aff.obj"), file_type='obj')
        scene_mesh.export(self.mesh_dir / (name + "_scene.obj"), file_type='obj')
##

The function to log scene and aff mesh is shown as above, I try to print aff_mesh and it shows like:
##
<trimesh.Scene(len(geometry)=3)>
##
which means it has object, but I can not log it. I'm wondering why?

Q2. when we log the info, there's two folder, one is meshes which contains meshes, the other one is a folder named as 'scenes', contain some .npz, I'm wondering what is the difference between the meshes we get and the .npz file which is the tsdf, is that just different representation of the same scene?

Q3. how can I visualize the grasp like the amazing visualization in your paper, with green and blue grippers for success and fail predictions.

Thanks for your time, very appreciate about your contribution again!

**Comment by Steve-Tod** [comment]
Q1. I'm not sure why `scene_mesh` is saved but `aff_mesh` is not, especially as you described, `aff_mesh` is not empty. I would try printing the `self.mesh_dir / (name + "_aff.obj"` and check if such file exist after `aff_mesh.export(self.mesh_dir / (name + "_aff.obj"), file_type='obj')`.

Q2. Yes, just different representations of the same scene.

Q3. From what I remember, you can try running [this script](https://github.com/UT-Austin-RPL/GIGA/blob/main/scripts/sim_grasp_save_scene.py) to save the visualizations of the scene. You might need some post-processing and rendering to get the visualization.
