### ISSUE TITLE
Downloadable Training Data

### ISSUE THREAD

**Issue by djl11** [UT-Austin-RPL/GIGA#3]
It would be very useful to have the training data returned from `generate_data_parallel.py` script available to download, for both the pile and packed cases.

I appreciate this may be a large amount of memory, and therefore difficult to host, so there is no expectation of course!
But it would avoid people needing to run the costly data generation process locally in order to experiment with the training.

**Comment by Steve-Tod** [comment]
Hi, I upload the link of data we generated [here](https://github.com/UT-Austin-RPL/GIGA#pre-trained-models-and-pre-generated-data). Hopefully it would be helpful.

**Comment by djl11** [comment]
Great, thanks a lot!

**Comment by djl11** [comment]
Hey, quick heads up. The links in the table for the README are mis-matched. The pile links leads to packed data, and vice versa. Also a small type for the word "this" beforehand. Both should be easy to fix! :)

**Comment by Steve-Tod** [comment]
Thank you for reminding me!

**Comment by Andyyoung0507** [comment]
When using a browser to download a dataset, the download process is often interrupted due to network problems. I tried to download it using aria2, but the download link was not recognized successfully. Are there any other ways to download the dataset?
Thanks for your excellent work!

**Comment by Steve-Tod** [comment]
Hi @Andyyoung0507 I added direct download link in [https://github.com/UT-Austin-RPL/GIGA/blob/main/README.md#pre-generated-data](https://github.com/UT-Austin-RPL/GIGA/blob/main/README.md#pre-generated-data). You can try download the data with `wget`.

**Comment by Andyyoung0507** [comment]
Thanks for all your help!
