### ISSUE TITLE
The time to generate the training set

### ISSUE THREAD

**Issue by TAO-TAO-TAO-TAO-TAO** [UT-Austin-RPL/GIGA#32]
Hello, may I ask some questions about datasets? Does the dataset used to train the model contain one million positive samples and one million negative samples? How much time does it take to generate these datasets in total?

**Comment by Steve-Tod** [comment]
Hi, I honestly do not remember the exact time. We run multiprocessing on multiple CPU machines to generate the data. In my rough memory, it takes less than 3 days.
