### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ccc1711** [UT-Austin-RPL/GIGA#4]
Hi,thank you for you repo!
However, I encountered an error when running  sim_grasp_multiple.py.
As shown in the figure 
![2021-06-25 11-36-58屏幕截图](https://user-images.githubusercontent.com/71708754/123365836-adfa8d80-d5a9-11eb-9b83-9e12765765de.png)

Could you give me some suggestions？

**Comment by Steve-Tod** [comment]
Sorry, I can't see why this is happening without any traceback. Maybe try `pdb` and see where this error comes from?

**Comment by ccc1711** [comment]
I try to use ipdb to find out where the problem is，I found that when running to line 86 or line 90, the error will occur 
![2021-06-25 15-15-34屏幕截图](https://user-images.githubusercontent.com/71708754/123386242-068d5300-d5c9-11eb-9550-5db803a438f8.png)

**Comment by ccc1711** [comment]
More specifically
![2021-06-25 17-12-58屏幕截图](https://user-images.githubusercontent.com/71708754/123400891-d0f06600-d5d8-11eb-8394-db84f1f07503.png)

**Comment by ccc1711** [comment]
It's very interesting.I solved this problem by installing open3d==0.12.0, the previous version was 0.13.0.

**Comment by Steve-Tod** [comment]
Great! I was using open3d==0.12.0. 
https://github.com/UT-Austin-RPL/GIGA/blob/a60495be5091e08019da66194adaf9588abb4352/environment.yaml#L101 
Let me add this to README.

**Comment by wuzeww** [comment]
> It's very interesting.I solved this problem by installing open3d==0.12.0, the previous version was 0.13.0.

hello! I want to know that if your experimental results are consistent with the success rate in the paper. The results i reproduced were 5% lower than the paper.

**Comment by ccc1711** [comment]
> > It's very interesting.I solved this problem by installing open3d==0.12.0, the previous version was 0.13.0.
> 
> hello! I want to know that if your experimental results are consistent with the success rate in the paper. The results i reproduced were 5% lower than the paper.
Hello！I also encountered this problem you mentioned. But it seems that my success rate is lower in the sence of pile and packed.Only when the object is blocks, the success rate will be the same as in the paper

**Comment by Steve-Tod** [comment]
Hi guys, are you using the pre-trained model I shared or you train the model again by yourself?

**Comment by wuzeww** [comment]
hi, I verified it with the model trained by myself. The result is 5% lower than the paper. And i also used the model you shared, the results are almost close the paper.



---Original---
From: "Zhenyu ***@***.***&gt;
Date: Thu, Jul 8, 2021 15:28 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [UT-Austin-RPL/GIGA] Segmentation fault (core dumped) (#4)




 
Hi guys, are you using the pre-trained model I shared or you train the model again by yourself?

**Comment by wuzeww** [comment]
> Hi guys, are you using the pre-trained model I shared or you train the model again by yourself?

I found some interesting things. When I only use the CPU to train 5 epochs, the result is better than 10 epochs under the GPU. The training parameters are the same as those given in the project

**Comment by Steve-Tod** [comment]
> > Hi guys, are you using the pre-trained model I shared or you train the model again by yourself?
> 
> I found some interesting things. When I only use the CPU to train 5 epochs, the result is better than 10 epochs under the GPU. The training parameters are the same as those given in the project

I've never use CPU for training. And the model I released was trained for 20 epochs. I just found the default argument is 10 epoches. That might be the problem😂.

**Comment by wuzeww** [comment]
> > > Hi guys, are you using the pre-trained model I shared or you train the model again by yourself?
> > 
> > 
> > I found some interesting things. When I only use the CPU to train 5 epochs, the result is better than 10 epochs under the GPU. The training parameters are the same as those given in the project
> 
> I've never use CPU for training. And the model I released was trained for 20 epochs. I just found the default argument is 10 epoches. That might be the problem.

okay, thank you very much.
