### ISSUE TITLE
How

### ISSUE THREAD

**Issue by wuzeww** [UT-Austin-RPL/GIGA#8]
Are giga, vgn and giga-aff are the same epoches? Are they all 20 epoches?

**Comment by Steve-Tod** [comment]
Yeah, I think so.

**Comment by wuzeww** [comment]
But the result of GIGA-Aff is higher than the paper.

**Comment by wuzeww** [comment]
I am currently making a graduation project based on your thesis, so I am eager to know the specific epochs of your work.   You can also reply me by email 1347485953@qq.com.
Extremely grateful！

**Comment by Steve-Tod** [comment]
> But the result of GIGA-Aff is higher than the paper.

That's possible, different devices and different random seeds can give different results. I suggest running more tests with more different random seeds. BTW, how much higher?

**Comment by wuzeww** [comment]
5 or 6 percentage points

**Comment by Steve-Tod** [comment]
Is that the average result from multiple random seeds?

**Comment by wuzeww** [comment]
Yes, the random seeds are [0, 1, 2, 3, 4]. The epoches are 20. I tested twice, the results were both higher than the paper.

**Comment by Steve-Tod** [comment]
Hmmm, how about the result of GIGA? Is it better than GIGA-Aff?

**Comment by wuzeww** [comment]
emm,&nbsp;the&nbsp;result&nbsp;of&nbsp;GIGA-Aff&nbsp;sometimes&nbsp;are&nbsp;better&nbsp;than&nbsp;GIGA.&nbsp;About&nbsp;1&nbsp;percent.


---Original---
From: &quot;Zhenyu ***@***.***&gt;
Date: Wed, Oct 27, 2021 06:42 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;&quot;State ***@***.***&gt;;
Subject: Re: [UT-Austin-RPL/GIGA] How (Issue #8)




 
Hmmm, how about the result of GIGA? Is it better than GIGA-Aff?
 
&mdash;
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Steve-Tod** [comment]
Hmmm, that's weird. Have you checked the loss curve and made sure they both converged?

**Comment by wuzeww** [comment]
### **This is the loss graph of GIGA-Aff training 20 epoches**

![2021-10-28 09-59-19 的屏幕截图](https://user-images.githubusercontent.com/44798683/139174227-62269f9a-adb1-4062-b40f-77ef30873fb7.png)

### **This is the 10 epoches**

![2021-10-28 09-59-26 的屏幕截图](https://user-images.githubusercontent.com/44798683/139174355-29153f68-0325-44b5-8979-e39adc479099.png)

**Comment by wuzeww** [comment]
Hi,

I trained GIGA-Aff for 10 epoches, the result is higher 5 percentage points than the paper. I wonder if there is a problem with the code.

**Comment by Steve-Tod** [comment]
How about the training figure of GIGA? Have you trained GIGA?

**Comment by wuzeww** [comment]
This the loss curve of giga:
![2021-10-30 20-51-43 的屏幕截图](https://user-images.githubusercontent.com/44798683/139533551-8aad669b-ddd2-43af-b892-5925863b9a01.png)

**Comment by Steve-Tod** [comment]
So the GIGA trained with the same number of epochs perform worse than GIGA-Aff?

**Comment by wuzeww** [comment]
yes



---Original---
From: "Zhenyu ***@***.***&gt;
Date: Sun, Oct 31, 2021 05:10 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [UT-Austin-RPL/GIGA] How (Issue #8)




 
So the GIGA trained with the same number of epochs perform worse than GIGA-Aff?
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Steve-Tod** [comment]
Hmmm, that's weird. What scenario are you using? Packed or pile?

**Comment by wuzeww** [comment]
packed.
Is the cause of network instability?



---Original---
From: "Zhenyu ***@***.***&gt;
Date: Mon, Nov 1, 2021 03:11 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [UT-Austin-RPL/GIGA] How (Issue #8)




 
Hmmm, that's weird. What scenario are you using? Packed or pile?
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Steve-Tod** [comment]
Not sure about that. GIGA should perform better than GIGA-Aff, especially in packed scenarios.

**Comment by wuzeww** [comment]
Sorry to reply you now.

It's weird. I retrained giga-aff, and the result was lower than before, even lower than the paper.

**Comment by Steve-Tod** [comment]
Do you retrain with the same setting?

**Comment by wuzeww** [comment]
on the different computer



---Original---
From: "Zhenyu ***@***.***&gt;
Date: Wed, Nov 3, 2021 23:23 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [UT-Austin-RPL/GIGA] How (Issue #8)




 
Do you retrain with the same setting?
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Steve-Tod** [comment]
The absolute value may vary because the test scenes can be different, but the relative performance between GIGA and GIGA-Aff should stay the same. However, you said GIGA is worse than GIGA-Aff previously, which is very weird. Did you train GIGA and GIGA-Aff on the same computer?

**Comment by wuzeww** [comment]
> The absolute value may vary because the test scenes can be different, but the relative performance between GIGA and GIGA-Aff should stay the same. However, you said GIGA is worse than GIGA-Aff previously, which is very weird. Did you train GIGA and GIGA-Aff on the same computer?

Yes, I trained them on the same computer before. Training the same model on the same computer, the loss curve obtained is different.

**Comment by wuzeww** [comment]
> The absolute value may vary because the test scenes can be different, but the relative performance between GIGA and GIGA-Aff should stay the same. However, you said GIGA is worse than GIGA-Aff previously, which is very weird. Did you train GIGA and GIGA-Aff on the same computer?

Yes, I trained them on the same computer before. Training the same model on the same computer, the loss curve obtained is different.

**Comment by Steve-Tod** [comment]
The loss curve can be different. I think training on different computers is OK. The important thing is testing on the same computer so that after fixing the random seed, the generated scenes will be the same. (I should have asked if you test them on the same computer, it was a typo.)

**Comment by wuzeww** [comment]
I tested them on the same computer.



---Original---
From: "Zhenyu ***@***.***&gt;
Date: Fri, Nov 5, 2021 23:23 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [UT-Austin-RPL/GIGA] How (Issue #8)




 
The loss curve can be different. I think training on different computers is OK. The important thing is testing on the same computer so that after fixing the random seed, the generated scenes will be the same. (I should have asked if you test them on the same computer, it was a typo.)
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Steve-Tod** [comment]
Not sure why this happens. I'll look back to this and re-train by myself later.

**Comment by wuzeww** [comment]
thank you very much.
比心🙆，非常感谢！



---Original---
From: "Zhenyu ***@***.***&gt;
Date: Fri, Nov 5, 2021 23:43 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [UT-Austin-RPL/GIGA] How (Issue #8)




 
Not sure why this happens. I'll look back to this and re-train by myself later.
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
