### ISSUE TITLE
Training speed is too slow

### ISSUE THREAD

**Issue by huaji98** [UT-Austin-RPL/GIGA#9]
Hi,I training one epoch on pile scene,and estimated time to spend more than 10 hours.

Here is my computer configuration：
pytorch 1.7.0    py3.8_cuda10.2.89_cudnn7.6.5_0
GPU:GeForce RTX 2070SUPER
CPU:Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
Memory:16G
Hard Disk Drive:1T HDD

Here are some screenshots:
![2021-11-03 20-16-23 的屏幕截图](https://user-images.githubusercontent.com/34676402/140060464-c6b2cba3-7131-459d-9818-83d0bc72b182.png)
![2021-11-03 20-16-30 的屏幕截图](https://user-images.githubusercontent.com/34676402/140060492-88dec9fb-f909-45a9-9e73-818a4a519d8d.png)
![2021-11-03 20-16-32 的屏幕截图](https://user-images.githubusercontent.com/34676402/140060514-565a0c40-228c-4b0e-9ac0-dc2068e808b5.png)
![2021-11-03 20-16-32 的屏幕截图-1](https://user-images.githubusercontent.com/34676402/140060537-ed235f01-7858-4f28-a2c1-32ff13491f20.png)

I found that GPU utilization was erratic and was 0 for a long time, and CPU utilization was not very high. So I presume it's because the io speed of the HDD hard disk drive is too slow.

I hope you can help me find the problem, thanks!

**Comment by Steve-Tod** [comment]
I guess you are right, the speed of io is too slow. One thing you can try to verify this guess is to iterate the dataloader without training and check the speed.

**Comment by huaji98** [comment]
yes,I found that loading the data took about the same amount of time as before with training.

**Comment by Steve-Tod** [comment]
Do you get a similar speed when training giga-aff? If not, then the IO bottleneck is the occupancy data loading. The default size of each occupancy data file is 100K points, but we only sample 2048 points. So one thing you can try is to decrease the size and increase the number of occupancy files when generating data:

`python scripts/save_occ_data_parallel.py /path/to/raw/data {number_of_points_per_file} {number_of_files} --num-proc 40`

**Comment by huaji98** [comment]
> Do you get a similar speed when training giga-aff? If not, then the IO bottleneck is the occupancy data loading. The default size of each occupancy data file is 100K points, but we only sample 2048 points. So one thing you can try is to decrease the size and increase the number of occupancy files when generating data:
> 
> `python scripts/save_occ_data_parallel.py /path/to/raw/data {number_of_points_per_file} {number_of_files} --num-proc 40`

Thank you for your reply. I found a more powerful computer, and now the training speed is normal！
